FROM ubuntu:22.04

ARG PYTHON_VERSION="3.9.17"
ARG SCALA_VERSION="2.12.10"
ARG PYTHON_TGZ_URL="https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tgz"


ENV DEBIAN_FRONTEND noninteractive
ENV LANG=en_US.UTF-8

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -q -y openjdk-8-jdk \
    libsnappy-dev \
    language-pack-en \
    supervisor \
    libsqlite3-dev \
    gcc \
    make \
    git \
    wget \
    zlib1g-dev \
    libffi-dev \
    openssl \
    libssl-dev \
    libbz2-dev \
    musl-dev \
    bzip2 \
    ca-certificates \
    curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install OpenJDK
RUN apt-get update && apt-get install -y --no-install-recommends \
    openjdk-8-jdk \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install Python
RUN wget "${PYTHON_TGZ_URL}" && \
    tar xvf "Python-${PYTHON_VERSION}.tgz" && \
    cd "Python-${PYTHON_VERSION}" && \
    ./configure --enable-optimizations && \
    make -j $(nproc) && \
    make altinstall && \
    cd .. && \
    rm -rf "Python-${PYTHON_VERSION}" "Python-${PYTHON_VERSION}.tgz"

RUN ln -s /usr/bin/python3 /usr/bin/python

# Install Scala
RUN wget "https://downloads.typesafe.com/scala/${SCALA_VERSION}/scala-${SCALA_VERSION}.tgz" && \
    tar -xvzf "scala-${SCALA_VERSION}.tgz" && \
    mv "scala-${SCALA_VERSION}" /usr/local/scala && \
    rm "scala-${SCALA_VERSION}.tgz"


RUN wget https://bootstrap.pypa.io/get-pip.py && \
    python get-pip.py && \
    rm get-pip.py

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

ENV PATH="/usr/local/scala/bin:$PATH"

RUN ["python", "--version"]
