version: "3.7"
services:  
    postgres:
        image: postgres:9.6
        volumes:
            - ./docker/docker-postgres/pg-init-scripts:/docker-entrypoint-initdb.d
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        ports:
            - "5432:5432"

    webserver:
        image: data-etl-airflow
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./data:/usr/local/airflow/data
        ports:
            - "8080:8282"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
            
    # Spark with 3 workers
    spark:
        image: data-etl-spark
        user: root
        environment:
            - SPARK_MODE=master
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
        volumes:
            - ./docker/docker-spark/app:/home/workspace/app
            - ./docker/docker-spark/jars:/home/workspace/jars
            - ./data:/home/workspace/data
            - ./docker/docker-spark/conf/spark-env.sh:/opt/bitnami/spark/conf/spark-env.sh
        ports:
            - "8181:8080"
            - "7077:7077"

    spark-worker-1:
        image: data-etl-spark
        depends_on:
            - spark
        environment:
            - SPARK_MODE=worker
            - SPARK_MASTER_URL=spark://spark:7077
            - SPARK_WORKER_MEMORY=2G
            - SPARK_WORKER_CORES=2
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
        volumes:
            - ./docker/docker-spark/app:/home/workspace/app
            - ./docker/docker-spark/jars:/home/workspace/jars
            - ./docker/docker-spark/conf/spark-env.sh:/opt/bitnami/spark/conf/spark-env.sh

    spark-worker-2:
        image: data-etl-spark
        depends_on:
            - spark
        environment:
            - SPARK_MODE=worker
            - SPARK_MASTER_URL=spark://spark:7077
            - SPARK_WORKER_MEMORY=2G
            - SPARK_WORKER_CORES=2
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
        volumes:
            - ./docker/docker-spark/app:/home/workspace/app
            - ./docker/docker-spark/jars:/home/workspace/jars
            - ./docker/docker-spark/conf/spark-env.sh:/opt/bitnami/spark/conf/spark-env.sh

