FROM data-etl-base:latest AS airflow_base

USER root
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    emacs \
    && apt-get autoremove -yqq --purge \
    && apt-get clean \
    && rm -rf "/var/lib/apt/lists/*" \
    && apt install wget -y

# Install additional packages
RUN pip install --upgrade pip && \
    pip install apache-airflow==2.9.0 pyspark==3.2.1 'sqlalchemy>=1.4.36,<2.0' psycopg2-binary==2.9.6

FROM airflow_base AS final

ENV SPARK_HOME /usr/local/spark
ARG SPARK_VERSION=3.2.1
ARG HADOOP_VERSION=3.2

RUN cd "/tmp" && \
    curl https://archive.apache.org/dist/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz -o spark.tgz && \
    tar -xvzf spark.tgz && \
    mkdir -p "${SPARK_HOME}/bin" "${SPARK_HOME}/assembly/target/scala-2.12/jars" && \
    cp -a /tmp/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}/bin/* "${SPARK_HOME}/bin/" && \
    cp -a /tmp/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}/jars/* "${SPARK_HOME}/assembly/target/scala-2.12/jars/" && \
    rm -rf /tmp/spark.tgz /tmp/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}

ENV PATH $PATH:/usr/local/spark/bin

EXPOSE 8080 5555 8793

ARG AIRFLOW_USER_HOME=/usr/local/airflow
ENV AIRFLOW_HOME=${AIRFLOW_USER_HOME}

WORKDIR ${AIRFLOW_USER_HOME}