version: "3.7"
services:  
    # postgres used by airflow
    postgres:
        image: postgres:9.6
        networks:
            - default_net
        volumes: 
            # Create Test database on Postgresql
            - ./docker-airflow/pg-init-scripts:/docker-entrypoint-initdb.d
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        ports:
            - "5432:5432"

    # airflow LocalExecutor
    airflow-webserver:
        image: docker-airflow-spark:1.10.7_3.0.1
        restart: always
        networks:
            - default_net
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        privileged: true
        volumes:
            - ../dags:/usr/local/airflow/dags #DAG folder
            - ../spark/app:/usr/local/spark/app #Spark Scripts (Must be the same path in airflow and Spark Cluster)
            - resources-data:/usr/local/spark/resources #Resources folder (Must be the same path in airflow and Spark Cluster)
            - ../spark/src/jars:/usr/local/spark/resources/jars
            - ../spark/src/python:/usr/local/spark/resources/python
        ports:
            - "8282:8282"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    # Spark with 3 workers
    spark:
        image: bitnami/spark:3.0.1
        user: root # Run container as root container: https://docs.bitnami.com/tutorials/work-with-non-root-containers/
        hostname: spark
        networks:
            - default_net
        environment:
            - SPARK_MODE=master
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
        privileged: true
        volumes:
            - ../spark/app:/usr/local/spark/app # Spark scripts folder (Must be the same path in airflow and Spark Cluster)
            - resources-data:/usr/local/spark/resources #Resources folder (Must be the same path in airflow and Spark Cluster)
            - ../spark/src/jars:/usr/local/spark/resources/jars
        ports:
            - "8181:8080"
            - "7077:7077"

    spark-worker-1:
        image: bitnami/spark:3.0.1
        user: root
        networks:
            - default_net
        environment:
            - SPARK_MODE=worker
            - SPARK_MASTER_URL=spark://spark:7077
            - SPARK_WORKER_MEMORY=1G
            - SPARK_WORKER_CORES=1
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
        privileged: true
        volumes:
            - ../spark/app:/usr/local/spark/app # Spark scripts folder (Must be the same path in airflow and Spark Cluster)
            - resources-data:/usr/local/spark/resources #Resources folder (Must be the same path in airflow and Spark Cluster)
            - ../spark/src/jars:/usr/local/spark/resources/jars

    spark-worker-2:
        image: bitnami/spark:3.0.1
        user: root
        networks:
            - default_net
        environment:
            - SPARK_MODE=worker
            - SPARK_MASTER_URL=spark://spark:7077
            - SPARK_WORKER_MEMORY=1G
            - SPARK_WORKER_CORES=1
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
        privileged: true
        volumes:
            - ../spark/app:/usr/local/spark/app # Spark scripts folder (Must be the same path in airflow and Spark Cluster)
            - resources-data:/usr/local/spark/resources #Resources folder (Must be the same path in airflow and Spark Cluster)
            - ../spark/src/jars:/usr/local/spark/resources/jars

    spark-worker-3:
        image: bitnami/spark:3.0.1
        user: root
        networks:
            - default_net
        environment:
            - SPARK_MODE=worker
            - SPARK_MASTER_URL=spark://spark:7077
            - SPARK_WORKER_MEMORY=1G
            - SPARK_WORKER_CORES=1
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
        privileged: true
        volumes:
            - ../spark/app:/usr/local/spark/app # Spark scripts folder (Must be the same path in airflow and Spark Cluster)
            - resources-data:/usr/local/spark/resources #Resources folder (Must be the same path in airflow and Spark Cluster)
            - ../spark/src/jars:/usr/local/spark/resources/jars

    #Jupyter notebook
    jupyter-spark:
        image: jupyter/all-spark-notebook:lab-3.0.16
        networks:
            - default_net
        ports:
            - "8888:8888"
            - "4040-4080:4040-4080"
        volumes:
            - ../notebooks:/home/jovyan/work/notebooks/
            - ../spark/src/jars:/usr/local/spark/resources/jars
volumes:
    resources-data:
        external: true

networks:
    default_net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.16.57.0/24
